# Generated by Django 3.0.2 on 2020-03-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=54),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
