# Generated by Django 3.0.2 on 2020-03-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_auto_20200312_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=23)),
                ('status', models.CharField(max_length=4)),
                ('rate', models.CharField(max_length=22)),
                ('volume', models.CharField(max_length=34)),
            ],
        ),
    ]
