# Generated by Django 3.0.2 on 2020-03-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0003_sensordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('message', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='height',
            field=models.FloatField(max_length=3),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='rate',
            field=models.FloatField(max_length=12),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='status',
            field=models.BooleanField(max_length=4),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='volume',
            field=models.FloatField(max_length=32),
        ),
    ]
