# Generated by Django 3.0.2 on 2020-03-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0004_auto_20200314_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
