# Generated by Django 3.0.2 on 2020-03-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0006_techdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=50)),
                ('block_number', models.CharField(max_length=89)),
                ('block_meter_reader', models.CharField(max_length=60)),
                ('block_total_customers', models.CharField(max_length=30)),
                ('block_av_usage', models.FloatField(max_length=20)),
            ],
        ),
    ]
