# Generated by Django 3.0.2 on 2020-03-14 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0007_blockdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigntech',
            name='name',
        ),
        migrations.RemoveField(
            model_name='assigntech',
            name='phone',
        ),
        migrations.AddField(
            model_name='assigntech',
            name='techDetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_register.TechDetails'),
        ),
    ]
