# Generated by Django 3.0.2 on 2020-03-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0008_auto_20200314_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigntech',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_register.Employee'),
        ),
    ]
