# Generated by Django 3.0.2 on 2020-03-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0009_assigntech_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigntech',
            name='employee',
        ),
        migrations.AddField(
            model_name='assigntech',
            name='employee',
            field=models.ManyToManyField(null=True, to='employee_register.Employee'),
        ),
    ]
