# Generated by Django 3.0.2 on 2020-03-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0012_auto_20200314_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockdetails',
            name='block_total_customers',
            field=models.FloatField(max_length=30),
        ),
    ]
