# Generated by Django 3.0.2 on 2020-03-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0013_auto_20200316_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockdetails',
            name='block_total_customers',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='height',
            field=models.IntegerField(max_length=3),
        ),
    ]
