# Generated by Django 3.0.2 on 2020-03-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0015_auto_20200316_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockdetails',
            name='block_total_customers',
            field=models.CharField(max_length=23),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='height',
            field=models.CharField(max_length=21),
        ),
    ]
