# Generated by Django 3.0.2 on 2020-03-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0020_auto_20200323_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='height',
            field=models.CharField(max_length=21),
        ),
    ]
