# Generated by Django 3.0.2 on 2020-03-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0021_auto_20200323_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockdetails',
            name='block_total_customers',
            field=models.IntegerField(),
        ),
    ]
