# Generated by Django 3.0.2 on 2020-05-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0022_auto_20200324_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='techdetails',
            name='messag',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
