# Generated by Django 3.0.2 on 2020-05-26 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0023_techdetails_messag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techdetails',
            name='messag',
        ),
    ]
