# Generated by Django 3.0.2 on 2020-07-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0024_remove_techdetails_messag'),
    ]

    operations = [
        migrations.AddField(
            model_name='techdetails',
            name='task',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
