# Generated by Django 3.0.2 on 2020-07-08 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0025_techdetails_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('task', models.CharField(max_length=500)),
                ('task_created', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_register.Employee')),
            ],
        ),
    ]
