# Generated by Django 3.0.2 on 2020-07-08 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0027_auto_20200708_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='task_list',
            field=models.CharField(default=django.utils.timezone.now, max_length=2100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
