# Generated by Django 3.0.2 on 2020-07-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0028_auto_20200708_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
