# Generated by Django 3.0.2 on 2020-07-09 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0029_employee_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='task_list',
        ),
    ]
